version: 2

sources:
  - name: northwind_etl
    tables:
      - name: orders
      - name: customers
      - name: suppliers
      - name: shippers
      - name: order_details
      - name: products